name: Build/Push Image

on:
  release:
    types: [published]
  pull_request:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push image [true|false]'
        required: false
        default: 'false'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/winxuu

jobs:
  build:
    name: Build Multi-Arch Stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event.inputs.push != 'false' }}
          platforms: linux/amd64,linux/arm64,linux/arm
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:{{ env.RELEASE_VERSION }}
          provenance: false
